# Generated by Django 3.0.7 on 2020-07-10 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorieslink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Homelink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('path', models.CharField(max_length=250, unique=True)),
                ('crated_dt', models.DateField(auto_now=True)),
                ('categorie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Home.categorieslink')),
            ],
        ),
    ]
